# The URL the site will be built for
base_url = "https://iroh.computer"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
[[extra.docs_sidebar]]
section = "Iroh"
links = [
  { title = "Overview", path = "/docs/"},
  { title = "Install", path = "/docs/install" },
  { title = "CLI", path = "/docs/cli" },
]

[[extra.docs_sidebar]]
section = "Beetle"
links = [
  { title = "Overview", path = "/docs/beetle" },
  { title = "Install", path = "/docs/beetle/install" },
  { title = "Services", path = "/docs/beetle/services" },
  { title = "CLI", path = "/docs/beetle/cli" },
  { title = "Data Locations", path = "/docs/beetle/data-locations" },
  { title = "Beetle & Kubo (go-IPFS)", path = "/docs/beetle/beetle-and-kubo" },
]

[[extra.design_docs_sidebar]]
section = "Iroh Design Documents"
links = [
  { title = "0. Introduction", path = "/design" },
  { title = "1. Iroh", path = "/design/iroh" },
  { title = "2. Content Addressing", path = "/design/content-addressing" },
  { title = "3. DSHT", path = "/design/dsht" },
  { title = "4. Data Transfer", path = "/design/data-transfer" },
  # { title = "concepts", path = "/design/concepts" },
  # { title = "FAQ", path = "/design/faq" },
  # { title = "For IPFS Veterans", path = "/design/for-ipfs-veterans" },
]